### ISSUE TITLE
Rename `MailerAssertionsTrait.php` to `MailerTrait.php`?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-symfony#123]
Don't know if it's worth it, but the name "Assertions" isn't semantically right there, cause 2 of the 4 function are grabbers and not assertions ;-)

**Comment by TavoNiievez** [comment]
> the name "Assertions" isn't semantically right there, cause 2 of the 4 function are grabbers and not assertions ;-)

I am aware of that.

However, that name was chosen based on Symfony's own nomenclature. This trait has an official namesake in Symfony, [check it out here](https://github.com/symfony/framework-bundle/blob/5.x/Test/MailerAssertionsTrait.php).

What really remains to be done is to add wrappers for those mail functions that are in Symfony, but they cannot be used (yet) in Codeception with the `$I->assert` syntax, this is because I have a pending work, which is to add assertions designed specifically for unit tests to the module.

So in the future the number of assertions in that trait will exceed the number of grabbers.

In any case, the other Traits also have the `~AssertionsTrait` suffix, so I prefer to keep those names as standardized as possible.

So...

> Rename `MailerAssertionsTrait.php` to `MailerTrait.php`?

I don't think so.

**Comment by TavoNiievez** [comment]
@ThomasLandauer thanks for opening
