### ISSUE TITLE
Token for amLoggedInAs should be configurable

### ISSUE THREAD

**Issue by codedge** [Codeception/module-symfony#165]
I am testing some functionality regarding login and logout with an external OpenID provider. For that, I depend on some attributes that are set on the token.
In Symfony Tokens can have so called _attributes_. See `TokenInterface` (https://github.com/symfony/security-core/blob/6.2/Authentication/Token/TokenInterface.php#L76).

When using this modules `amLoggedInAs` method, I cannot modify the returned token,
[This](https://github.com/Codeception/module-symfony/blob/main/src/Codeception/Module/Symfony/SessionAssertionsTrait.php#L51) token generation should be switched to an approach, where I can control the token, f. ex. setting some attributes on the token.

And so my logic, that depends on attributes for the token fails.

**Comment by TavoNiievez** [comment]
Hi @codedge ,

I understand.

The problem here is that the signature of the `amLoggedInAs` assertion already includes 3 different parameters. All of them needed to create the token in the first place.

I would agree to create a method that receives as parameter an object of type "`Symfony\Component\Security\Core\Authentication\Token\AbstractToken`" or of type "Symfony "Security" or of type "Symfony\Component\Security\Core\Authentication\Token\TokenInterface".
and create an auxiliary method that allows to create the token as before, depending on the 3 parameters `$user`, `$firewallName` and `$firewallContext`.
In this way:
$token = $I->createAuthenticationToken($user, $firewallName);
$I->amLoggedInWithToken($token);
This way you can do whatever you want with the `$token`, including assigning attributes to it before passing it to the `amLoggedIinWithToken` function.

What do you think of this approach?
Are you up for submitting a PR for this?

Thank you!

**Comment by codedge** [comment]
@TavoNiievez Sounds like a good solution to me. I would take care of this and provide a PR.

**Comment by codedge** [comment]
@TavoNiievez See #182
