### ISSUE TITLE
Rename all abbreviated function arguments to better support PHP8's Named Arguments

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-symfony#66]
If I'm understanding [PHP8's Named Arguments](https://www.php.net/releases/8.0/de.php?lang=de#named-arguments) right, instead of
```php
$I->seeInSession('name', 'Thomas');
```
...you can now do
```php
$I->seeInSession(value: 'Thomas', attrib: 'name');
```
The problem I'm seeing is that some functions have abbreviated/slang parameter names like `params` or `val` (instead of `parmeters` or `value`). If we change them **now**, it's no real BC break, since nobody (?) is using this feature yet. I'm suggesting this for the Symfony module first, to get started with a smaller "sub-project". https://github.com/Codeception/module-symfony/pull/65 is a first step.

Questions:

1. Do you agree in principle that all occurrences of `params` should be renamed to `parameters`?
2. Do you think that it's worth trying to do it automatically? Scrolling through `Symfony.php` I don't see *that* many occurrences, so doing it manually is probably faster in total?

**Comment by TavoNiievez** [comment]
> Do you agree in principle that all occurrences of params should be renamed to parameters?

<details>
<summary>Clic to see answer.</summary>
<br/>

**Disclaimer:** the following is just my *personal* opinion:

I disagree. changing 'params' to 'parameters' is just a style change. There is really no standard that says that to better support named arguments they must contain whole words. In fact, in the default php functions you see these abbreviations very often.

So I think this would be a trivial change.

What I could agree with is to be congruent and if 'params' is used, it is used throughout the module. But for this you would also have to change this in the other modules (and in all the code of Codeception also). Some of the functions that i included simply -copied- the nomenclature of the parameters in Laravel module to try to create a unified API between modules. The effort it would take to send PRs to all modules to change the abbreviations **(or keep them)** just don't think it compensates, or means a real objective improvement in readability.
Unless Codeception had defined a naming guide that everyone must follow, doing this would not be very useful, because in the future anyone could propose exactly the opposite of what you propose now and no one could actually contradict it.
</details>

**Comment by TavoNiievez** [comment]
Also note that the following functions also have abbreviations in their parameter names:
```php
public function amOnRoute(string $routeName, array $params = [])
public function seeCurrentRouteIs(string $routeName, array $params = [])
public function seeNumRecords(int $expectedNum, string $className, array $criteria = [])
public function amOnAction(string $action, array $params = [])
```

**Comment by TavoNiievez** [comment]
Hey @ThomasLandauer Can you justify that this change is not trivial?

You can ping another maintainer if you want a second opinion.

This issue and its linked pull request will be closed otherwise.

**Comment by ThomasLandauer** [comment]
Well, I don't have any other arguments other than that abbreviations are just bad practice *in general*. Even the Symfony docs switched from the ubiquitous `$em` to `$entityManager`: https://symfony.com/doc/current/doctrine.html#persisting-objects-to-the-database

But in the end it's a matter of personal taste ;-) @DavertMik @Naktibalda What do you say?

**Comment by TavoNiievez** [comment]
`$em` **is** a bad name.

Some static code analyzers such as phpmd define names for fields or parameters with a [length less than 3 characters to be bad practice](https://phpmd.org/rules/naming.html), but abbreviations that do not go below that limit are **not**.
